### ISSUE TITLE
Snapbox 0.3.1 Breaking Change in `\` normalization 

### ISSUE THREAD

**Issue by dbanty** [assert-rs/trycmd#119]
0.3.1 of Snapbox was a breaking change for me—as I'm using it to compare some generated TOML [here](https://github.com/knope-dev/knope/runs/7665020792?check_suite_focus=true). The `\` in these cases are not path separators, so should not be normalized.

If this is intentional, I can just replace my usage of `assert_eq_path` with a custom `Assert` that disables normalization—but I wanted to report the issue just in case it was unintentional.

Thanks!

**Comment by epage** [comment]
I assume that failure came from https://github.com/knope-dev/knope/pull/218 which is upgrading from 0.2.10 to 0.3.1, so breaking changes are allowed.

However, you should have already been seeing that in 0.2.  We normalize and text, including paths.  I'm looking into this to better understand what is happening.

However, in 0.3.1 we introduced a setting to control this, `normalize_paths`.  An example of it in use is at https://github.com/crate-ci/typos/blob/master/crates/varcon/tests/codegen.rs#L10

**Comment by epage** [comment]
9ba81239a39a2b457fd560af8dcd647ba8eb2ed2 is the commit that caused it to start failing

**Comment by epage** [comment]
Looking at the commit, it looks like we mean to only normalize paths in the "matches" case and not the "equal" case but in changing the code up, one of those got swapped.

Now that we have `normalize_paths`, I wonder if we should normalize paths for the equal case and not just the matches case.  That would involve updating the directory version to match what was done in 9ba81239a39a2b457fd560af8dcd647ba8eb2ed2

**Comment by epage** [comment]
btw the work in that commit was one step in a series of refactors for https://github.com/assert-rs/trycmd/issues/92 which would make it easier to diff toml, even if we still normalize.

**Comment by dbanty** [comment]
> I assume that failure came from https://github.com/knope-dev/knope/pull/218 which is upgrading from 0.2.10 to 0.3.1, so breaking changes are allowed.

I thought the tests were passing against 0.3.0 but I never merged that update, so I could be mistaken.

So is the path forward to normalize in all the places? Just wondering if I should start updating my tests to explicitly disable normalization.

**Comment by dbanty** [comment]
Looks like my tests are passing again under 0.3.2 🥳. Thanks!
