### ISSUE TITLE
Can't figure out how to get tests working

### ISSUE THREAD

**Issue by SUPERCILEX** [assert-rs/trycmd#136]
I added the lib and this test:

```rust
#[test]
fn readme_test() {
    trycmd::TestCases::new().case("README.md");
}
```

Running the test gives `Testing README.md ... ignored` with no explanation of why. Here's the repo in question: https://github.com/SUPERCILEX/ftzz

**Comment by SUPERCILEX** [comment]
Ah, apparently you need `console` in your ``` block. An example of a README test should be added to this repo to make that clearer.

**Comment by epage** [comment]
We have an example but somehow forgot to set the language on it.  Done.
