### ISSUE TITLE
Trim whitespace in readme output

### ISSUE THREAD

**Issue by SUPERCILEX** [assert-rs/trycmd#139]
I'm not sure if it's ok to trim whitespace in all output (since it'd be nice to have a tailing newline in some stdout file), so I'm thinking only trailing lines in readmes should be trimmed.

**Comment by epage** [comment]
The way I'm using this in clap, I very much want that trailing newline in the readme files.  We had very inconsistent trailing newlines until we adopted trycmd.

**Comment by SUPERCILEX** [comment]
In readme files? Would you mind sharing an example of where having a blank line before the closing ``` is helpful?

**Comment by epage** [comment]
First, in github rendering, it hasn't caused harm in my READMEs, like [cargo-edit](https://github.com/killercup/cargo-edit)

Second, I was referring to how it helped us catch clap bugs by having it in all of our examples, like [this output](https://raw.githubusercontent.com/clap-rs/clap/master/examples/demo.md).

**Comment by SUPERCILEX** [comment]
Ohhh, I see. You're saying that it should be consistent so you can catch whitespace bugs regardless of the position of the test. Makes sense to me.
