### ISSUE TITLE
Docs do a poor job of explain what this library does

### ISSUE THREAD

**Issue by SUPERCILEX** [assert-rs/trycmd#141]
It took me several hours to understand how this library worked... the docs need a lot of love.

- In the readme and intro docs, a test is added with that looks through `"tests/cmd/*.trycmd"` but no example is shown of a trycmd so I had no idea these files actually needed to exist (I thought TRYCMD=dump would create them and was very confused for a while). An example of the trycmd file is needed.
- It also needs to be mentioned that md files are interpreted the same way.
- The example [here](https://docs.rs/trycmd/latest/trycmd/#trycmd) makes no sense. It looks like that rust code will be compiled on the fly (it isn't) and where is `my-cmd` coming from? And how does the output make any sense? It says print hello world but then only hello is printed. This example needs to be completely reworked: it should clearly and explicitly be shown that you have a basic rust binary with a main function that prints something, an md/trycmd file that calls that binary (no need for input params), and a test that has the trycmd file as a case.
- Eliding content needs an example because I still can't figure out what it does: https://github.com/assert-rs/trycmd/issues/140

**Comment by epage** [comment]
See
- 0079aeeb1dbae09f111f72eb03a7602cc1ee15fc
- ff4c769268fb998959147ac46a4262864a62426d
- dceeaaa7c506221c50175d3531432096e50a2d78

**Comment by SUPERCILEX** [comment]
This is very disappointing: it misses the point that there should be a concrete example. You've *described* the example without actually providing a real example people can look at. Also it's deeply ironic to have [incorrect examples](https://github.com/assert-rs/trycmd/blob/dceeaaa7c506221c50175d3531432096e50a2d78/src/lib.rs#L123) because you aren't using the library you're trying to demo.

**Comment by epage** [comment]
> This is very disappointing: it misses the point that there should be a concrete example. 

This issue is not about a concrete example but specific pain points.  Feel free to create an issue about concrete examples

Roll up issues are not ideal because they are rarely ever "done", being a constant moving target.

**Comment by SUPERCILEX** [comment]
> Feel free to create an issue about concrete examples

Sure: #146
