### ISSUE TITLE
Don't do anything under miri?

### ISSUE THREAD

**Issue by SUPERCILEX** [assert-rs/trycmd#152]
AFAIU, trycmd is executing a pre-compiled binary so miri wouldn't do anything with the actual code under test. Every user could `#[cfg_attr(miri, ignore)]` their trycmd tests, but I wonder if it'd make more sense to just noop trycmd runs under miri.

**Comment by epage** [comment]
I think, if anything, we would mark all tests as ignored to help draw attention to it.
