### ISSUE TITLE
show extended information for unexpected status

### ISSUE THREAD

**Issue by ehuss** [assert-rs/trycmd#162]
Currently if a process exits with an unexpected signal, snapbox will say [interrupted](https://github.com/assert-rs/trycmd/blob/f3698b7834b84bca712f81bf2665b91bff34d531/crates/snapbox/src/cmd.rs#L883). It would be helpful to be able to see what the actual signal was, as that can be important information. 

I'd more or less like to copy [these lines](https://github.com/rust-lang/cargo/blob/7d8d02843013b9954dfbded8547816807ef1db72/crates/cargo-util/src/process_error.rs#L107-L185) over. I'm not sure if there is some simpler way to do that, or if it could depend on cargo-util.

**Comment by epage** [comment]
This is available in snapbox v0.4.1
