### ISSUE TITLE
confirming the purpose of `snap-fixture` binary (from `snapbox`), and that it is not intended for distribution

### ISSUE THREAD

**Issue by dkg** [assert-rs/trycmd#163]
I couldn't find any commentary or documentation  around the `snap-fixture` binary tool in the `snapbox` crate.

From following the code, it looks like this tool is just designed for use with the crate's test suites, but as far as i understand, it isn't likely to warrant wider distribution.

If this is right (or even if it isn't), it might be worth adding a comment or two in `Cargo.toml` or in `src/bin/snap-fixture.rs` with a short explanation of what the tool is and where it is expected to be useful)

(i ask this in the context of trying to prepare the snapbox crate for inclusion in debian, which is why i wanted to confirm)

Thanks for all the infrastructure work represented in these crates!

**Comment by epage** [comment]
This is used exclusively for snapbox's tests.  I've commented on it in both places.
