### ISSUE TITLE
Support for filtering tests with the TRYCMD environment variable

### ISSUE THREAD

**Issue by figsoda** [assert-rs/trycmd#187]
It would be nice for `TRYCMD` accept a list of separated variables to filter the tests, so
```bash
TRYCMD=dump=foo,bar cargo test test_name
```
would be equivalent to
```bash
TRYCMD=dump cargo test cli -- trycmd=foo trycmd=bar
```

And
```bash
TRYCMD==foo,bar cargo test cli
```
would be equivalent to
```bash
cargo test cli -- trycmd=foo trycmd=bar
```

**Comment by epage** [comment]
As we have a way to filter tests today, I'm hesitant to do this as it makes the `TRYCMD` variable more complex to explain and deal with

**Comment by figsoda** [comment]
fair enough
