### ISSUE TITLE
How to pass a variable argument to a test case?

### ISSUE THREAD

**Issue by loewenheim** [assert-rs/trycmd#202]
I want to test a command that modifies some files and snapshot its console output. My approach is to copy the test fixtures to a temporary directory and have the command work on that, but for that to work, I need to pass the tempdir path to the command. I can't figure out how to do this with `trycmd`.

Putting the path into an environment variable (say, `FIXTURES_PATH`) doesn't work. My `.trycmd` file contains
```
$ example-command $FIXTURES_PATH
```
but the environment variable isn't resolved; `$FIXTURES_PATH` is interpreted as a literal.

Is there another way this could be accomplished?

**Comment by epage** [comment]
So far, `trycmd` has not had *much* support for dynamic test fixtures.  I've generally used `snapbox` for that instead.

However, if I'm understanding correctly, your use case should be supported. trycmd has support for fixtures and verifying changes to them.  When loading a `foo.trycmd` file, we'll look for a fixture at `foo.in/` and choose that as the CWD.  **if** you also have a `foo.out/`, we won't just verify `foo.in/` was modified to look like it, we'll automatically copy `foo.in` to a temp directory and make that the CWD and then verify that temp directory against `foo.out/`
