### ISSUE TITLE
Documentation mismatch for snapbox::assert_eq

### ISSUE THREAD

**Issue by wyf18** [assert-rs/trycmd#211]
Hello! 🐙
While scanning crates.io. we noticed a document-code mismatch issue in this crate, we think the doc examples are generally meant to illustrate why someone would want to use the item.

# Location
documentation for snapbox::assert_eq
（https://docs.rs/snapbox/0.4.11/snapbox/fn.assert_eq.html）

# Summary
The example of the document does not mention the `assert_eq` function, but mention `assert_matches`, is it a doc-code mismatch?

I found in the commit 2c9dc63, the doc changed from right one to wrong, I wonder why?

We're doing an empirical study of documentation in the Rust ecosystem. 
Your answers will help us and better promote the development of the Rust ecosystem.

Thank you for checking out this issue! 👍🤗

**Comment by epage** [comment]
Thanks for pointing it out!

My best guess is copy/paste
