### ISSUE TITLE
Inline snapshot overwriting for snapbox

### ISSUE THREAD

**Issue by not-my-profile** [assert-rs/trycmd#221]
Snapbox currently only appears to support `SNAPSHOTS=overwrite` for `assert_eq_path` and `assert_matches_path` but not for inline snapshot assertions like `assert_eq` or `assert_matches`.

The popular [cargo-insta](https://crates.io/crates/cargo-insta) tool does support the updating of inline snapshots. So I think the current lack of support should certainly be documented.

If supporting inline snapshots is out of the scope of snapbox, I think a reference to Insta in the documentation would be nice.

If it is within scope of snapbox, reliably parsing Rust code would require a dependency on [syn](https://crates.io/crates/syn), which however could be feature-gated and disabled by default. The [inline::FilePatcher](https://github.com/mitsuhiko/insta/blob/428833326dca8bea6417a7ec909c13e52f2b5269/cargo-insta/src/inline.rs) implementation of cargo-insta looks quite brief, which would suggest that supporting this feature wouldn't take much additional code here.

**Comment by epage** [comment]
Thanks; its too easy to overlook crossing repo boundaries when linking

**Comment by epage** [comment]
As mentioned in #225, the new API I expect for this would be something like `assert_eq(data!("..."), ...)` which would also allow `assert_eq(Data::from_path("..."), ...)`, allowing the code to be unified between the snapshot being in-source vs external.

In fact, that API refactor can happen before the requisite cargo features are available.

**Comment by epage** [comment]
Oops, we had #135 for this.  Closing in favor of that.  #251 will close it.
