### ISSUE TITLE
Rename `assert_eq_path` and `assert_matches_path` in snapbox

### ISSUE THREAD

**Issue by not-my-profile** [assert-rs/trycmd#225]
I consider the current names to be highly confusing. They don't assert that a path is equal or that something matches a path ... I think it would make sense to rename them to `assert_file_eq` and `assert_file_matches`.

This would be a breaking change but I think well worth it.

**Comment by epage** [comment]
I consider this one of those "no win" situations with naming.  However, I expect this problem to go away with #221 because we'll instead say `assert_eq!(Data::path(path), ...)`

Because of that, I think I'll go ahead and close this

**Comment by not-my-profile** [comment]
Did you mean to link #221? I'm somewhat confused how that issue relates to `assert_eq!(Data::path(path), ...)`.

**Comment by not-my-profile** [comment]
https://github.com/assert-rs/trycmd/issues/227#issuecomment-1684408897

> I expect https://github.com/assert-rs/trycmd/issues/221 to change up the API in way that will make this clearer.

Ah ok ... nevermind.
