### ISSUE TITLE
snapbox uses green for removed and red for added lines

### ISSUE THREAD

**Issue by not-my-profile** [assert-rs/trycmd#228]
```rs
#[test]
fn snapbox() {
    snapbox::assert_eq("foo", "bar");
}
```

![screenshot of output](https://github.com/assert-rs/trycmd/assets/73739153/6899c304-9607-4102-b99a-95b1fd01b729)

**Comment by epage** [comment]
I'm always mixed on which way to go for this.

Generally, a diff will show  the removed text as red and the added text as green.

Here, the "good" state is the base of the diff and you generally represent "good" with "green".

**Comment by not-my-profile** [comment]
I appreciate that there is reasoning behind this decisions however I still consider the displaying of a diff with inversed colors to be *incredibly* confusing. Especially because both `pretty_assertions` and `similar-asserts` just use the regular diff colors.

When looking at a diff from an `assert_eq` I don't want to be forced to think to myself: "Does this assert_eq come from snapbox?" before I'm able to interpret the colors.

**Comment by marcospb19** [comment]
I agree that `diff` colors should be prioritized over `good/bar` colors for intuitiveness. However, that's probably a personal thing.
