### ISSUE TITLE
Comparing expected and actual output with Harness

### ISSUE THREAD

**Issue by smoelius** [assert-rs/trycmd#235]
I am trying to use `snapbox` to construct a set of tests where some setup is performed in a temporary directory, my binary is run, and the binary's actual output is compared to expected output.

But there are parts of the actual output that I want to ignore.

To that end, I was expecting `snapbox` to perform an [`assert_matches!`](https://docs.rs/snapbox/latest/snapbox/fn.assert_matches.html) like comparison between the contents of the file at `Case`'s [`expected`](https://github.com/assert-rs/trycmd/blob/6c50b1567695eac45b13526b5ed9b8ed2370e44a/crates/snapbox/src/harness.rs#L213) field and the actual output return by the [`test`](https://github.com/assert-rs/trycmd/blob/6c50b1567695eac45b13526b5ed9b8ed2370e44a/crates/snapbox/src/harness.rs#L60) function passed to `Harness::new`.

Put more simply, I was expecting `[..]` in the expected output to work like it does in `trycmd`.

But I see that's [not the case](https://github.com/assert-rs/trycmd/blob/6c50b1567695eac45b13526b5ed9b8ed2370e44a/crates/snapbox/src/harness.rs#L179-L182).

I could manually redact the actual output. But I wonder, is there a better way?

**Comment by smoelius** [comment]
I might be fooling myself, but I think this does the trick for me: https://github.com/smoelius/trycmd/commit/24eb092b0f93cb7bcd7f44b50ecb68a8bff5a323

**Comment by epage** [comment]
The code to use matching isn't in question but whether unconditional matching is appropriate here.

**Comment by smoelius** [comment]
> The code to use matching isn't in question but whether unconditional matching is appropriate here.

I'm sorry for misunderstanding. Is there a way that I can help answer that?

**Comment by epage** [comment]
Not directly.  We likely just need to make this configurable.  However, I feel like this part of snapbox hasn't been working out as well due to how hard it would likely be to get the needed flexibility and I've been tempted to remove it.
