### ISSUE TITLE
Full example of snapshot-testing a CLI binary?

### ISSUE THREAD

**Issue by willbuckner** [assert-rs/trycmd#86]
I'm brand new to `trycmd`, and would love to use it to snapshot test various combinations of args passed to a binary I'm building. However, despite the reputation of `trycmd` doing exactly this, I can't find a single example here of how to do that. Reading the example provided in `examples/`, there seems to be no binary involved. Even though I'll probably figure this out by looking at how various opensource projects use it on GitHub, I think providing an end-to-end working example of a binary that takes an argument, accepts input from stdin, and writes output to stdout, being snapshot tested end to end, would help a lot of others onboard to the project.

A potential example program might be a simple CLI app that reads stdin, reverses each line, and spits out the reversed lines to stdout.

**Comment by epage** [comment]
- [example of testing a CLI](https://github.com/assert-rs/trycmd/blob/main/tests/cli_tests.rs)
- [example f testing examples](https://github.com/assert-rs/trycmd/blob/main/tests/example_tests.rs)
- [crates that serve as examples](https://github.com/assert-rs/trycmd#users)

We should probably make this more discoverable in docs.rs

**Comment by willbuckner** [comment]
Looks great, thanks!
