### ISSUE TITLE
Option to check indentation of structured data

### ISSUE THREAD

**Issue by MiSawa** [assert-rs/trycmd#95]
CLIs who outputs structured data often format the data with some indentation. It'd be great to be able to check them along with the structure of the data (#93)

**Comment by epage** [comment]
Checking both indentation while analyzing higher level structure data is out of scope of the project, it'd require format-preserving parsers for each format and a lot of complexity.  Its probably best to focus some limited tests on the format and be simple enough to not need structured data comparisons from #93 and the rest on the content of the data and use #93.

(to clarify for my comment in #91, my intent had been to post your use case to #93 to remind us that allowing people to bypass structured data was important)
